kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
  namespace: default
rules:
  - apiGroups: ["", “extensions”, “apps”]
    resources: [“deployments”, “pods”, “services”]
    verbs: [“get”, “list”, “watch”, “create”, “update”, “patch”, “delete”]
