---
- name: Create a valid machine credential for github
  awx.awx.credential:
    name:                  '{{ ssh_machine_credential_name }}'
    credential_type:       'Machine'
    organization:          '{{ org_name }}'
    inputs:
      username:     '{{ ansible_user }}'
      ssh_key_data: '{{ secrets.awx.ssh_credentials.privateKey }}'
    controller_host:        '{{ awx_api_host }}'
    controller_oauthtoken:  '{{ awx_access_token0 }}'
  when: not ansible_check_mode
  tags:
    - awx
    - awx_ui

- name: Create a valid SCM credential for github
  awx.awx.credential:
    name:                  '{{ ssh_scm_credential_name }}'
    credential_type:        'Source Control'
    organization:          '{{ org_name }}'
    inputs:
      username:     'psolomon-services'
      ssh_key_data: '{{ secrets.awx.ssh_credentials.privateKey }}'
    controller_host:        '{{ awx_api_host }}'
    controller_oauthtoken:  '{{ awx_access_token0 }}'
  when: not ansible_check_mode
  tags:
    - awx
    - awx_ui

- name: Create a Vault credential
  awx.awx.credential:
    name:                   '{{ vault_credential_name }}'
    credential_type:        'Vault'
    organization:           '{{ org_name }}'
    validate_certs:         false
    inputs:
      # looks odd, but we bootstrap this with either prompting for password or using --vault-password-file
      vault_password: '{{ secrets.vault.vault_password }}'
    controller_host:        '{{ awx_api_host }}'
    controller_oauthtoken:  '{{ awx_access_token0 }}'
  when: not ansible_check_mode
  tags:
    - awx
    - awx_ui

- name: Create a Test Vault credential
  awx.awx.credential:
    name:                   '{{ vault_test_credential_name }}'
    credential_type:        'Vault'
    organization:           '{{ org_name }}'
    validate_certs:         false
    inputs:
      vault_password: 'mypassword'

    controller_host:        '{{ awx_api_host }}'
    controller_oauthtoken:  '{{ awx_access_token0 }}'
  when: not ansible_check_mode
  tags:
    - awx
    - awx_ui
