---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: gcr.io/google-samples/hello-app:1.0
          ports:
            - containerPort: 80

---
#kind: Service
#apiVersion: v1
#metadata:
#  name: my-service
#spec:
#  selector:
#    app: myapp
#  ports:
#  - protocol: TCP
#    port: 3000
#    nodePort: 32321
#  type: NodePort
