kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: blue-green-test-project
  namespace: argocd
  #annotations:
  #  argocd.argoproj.io/refresh: hard
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: blue-green-test-project
  source:
    path: apps/blue-green-test/yaml
    repoURL: git@github.com:psolomon-services/argocd-test
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
