apiVersion: v1
kind: Pod
metadata:
  name: my-csi-app
  #namespace: vault
spec:
  containers:
    - name: web-server
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: my-volume
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: ebs-claim
