---
apiVersion: v1
kind: Service
metadata:
  name: busybox
spec:
  ports:
  - name: tcp
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: busybox
  type: LoadBalancer
  #type: NodePort

