---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-test
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: longhorn-test
  namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-test
  namespace: default
  #labels:
  #  app: longhorn-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-test
  template:
    metadata:
      labels:
        app: longhorn-test
    spec:
      serviceAccountName: longhorn-test
      restartPolicy: Always
      containers:
      - name: longhorn-test
        image: nginx:stable-alpine
        imagePullPolicy: Always
        #livenessProbe:
        #  exec:
        #    command:
        #      - ls -al
        #      - /data
        #  initialDelaySeconds: 5
        #  periodSeconds: 5
        volumeMounts:
        - name: volv
          mountPath: /data
        ports:
        - containerPort: 80
      volumes:
      - name: volv
        persistentVolumeClaim:
          claimName: pjs-test-volume-2


#ansible@deploy:~/repos/argocd-test/install/longhorn$ kubectl get pvc -A
#NAMESPACE   NAME                                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
#awx         postgres-15-awx-demo-postgres-15-0   Bound    pvc-9b92bd45-57b8-43bc-885f-178948b67e9c   8Gi        RWO            standard       <unset>                 4d15h
#default     pjs-test-volume-2                    Bound    pvc-d9c7f8bb-65ca-44c9-9124-5e8dcaf2b501   2Gi        RWO            longhorn       <unset>                 5m12s
#jenkins     jenkins                              Bound    pvc-4dc4d105-dbd6-4b74-b4ec-71713c624760   8Gi        RWO            standard       <unset>                 9d
#ansible@deploy:~/repos/argocd-test/install/longhorn$ kubectl get pv -A
#NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                    STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE
#pvc-4dc4d105-dbd6-4b74-b4ec-71713c624760   8Gi        RWO            Delete           Bound    jenkins/jenkins                          standard       <unset>                          9d
#pvc-9b92bd45-57b8-43bc-885f-178948b67e9c   8Gi        RWO            Delete           Bound    awx/postgres-15-awx-demo-postgres-15-0   standard       <unset>                          4d15h
#pvc-d9c7f8bb-65ca-44c9-9124-5e8dcaf2b501   2Gi        RWO            Delete           Bound    default/pjs-test-volume-2                longhorn       <unset>                          5m12s

