apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pjs-test-volume-2
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-test
  resources:
    requests:
      storage: 2Gi
