# https://ansible.readthedocs.io/projects/awx-operator/en/latest/installation/basic-install.html
# https://devopscube.com/kustomize-tutorial/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  #- github.com/ansible/awx-operator/config/default?ref=2.16.1
  - github.com/ansible/awx-operator/config/default?ref=2.19.0
  - awx-demo.yaml
  - deploy-awx-job.yaml
  - api-ingress.yaml

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    #newTag: 2.16.1
    newTag: 2.19.0

#patches:
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/
#- patch: |-
#    - op: replace
#      # find in kustomize build .
#      path: /spec/template/spec/containers/1/imagePullPolicy
#      value: Always
#      namespace: awx
#  target:
#    #labelSelector: "app.kubernetes.io/name=awx-operator-controller-manager"
#    kind: Deployment
#    name: awx-operator-controller-manager
#    namespace: awx
