---
- name: Deploy an Nginx Server
  hosts:         nginx
  remote_user:   ansible
  gather_facts:  true
  become:        true

  tasks:
    - name: update
      apt: update_cache=yes

    - name: Install Nginx
      apt: name=nginx state=latest

      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=reloaded
