---
- name: Plex Setup SANDBOX
  hosts:         plex
  remote_user:   ansible
  gather_facts:  true

  vars_files:
    - group_vars/vault.yml

  vars:
    # recreate all docker containers and volume dirs when deploying (nginx-proxy, unbound, and pihole)
    - force_recreate_container:    true
    - force_recreate_volume_dirs:  true

  roles:
    - docker
    - nginx-proxy
    - plex
