# kubectl exec -n vault -it vault-0 -- vault kv put cubbyhole/pjs mysecret=wow

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: backend-secretstore
    kind: SecretStore
  target:
    name: mysecret           # the secret created
  data:
  - secretKey: mysecretkey   # key created inside the new secret
    remoteRef:
      key: /cubbyhole/pjs
      #key: provider-key
      version: v1
      property: mysecretkey
