apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: backend-secretstore
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      version: v1
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          #namespace: vault
