---
kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: pihole
  namespace: argocd
spec:
  description: Pihole Project
  sourceRepos:
    - '*'

  destinations:
  - namespace: pihole
    server:    https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind:  '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind:  '*'

  #roles:
  #- name: ci-role
  #  description: "Sync privs for dev-project"
  #  policies:
  #  - p, proj:dev-project:ci-role, applications, sync, dev-project/*, allow
  #  - p, proj:dev-project:ci-role, applications, get,  dev-project/*, allow
