apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-test
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: longhorn-test
  namespace: default

---
apiVersion: v1
kind: Pod
metadata:
  name: longhorn-test
  namespace: default
spec:
  affinity:
    nodeAffinity: null
  serviceAccountName: longhorn-test
  restartPolicy: Always
  containers:
  - name: longhorn-test
    image: nginx:stable-alpine
    imagePullPolicy: Always
    livenessProbe:
      exec:
        command:
          - ls -al
          - /data
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-pvc
