---
apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  containers:
  - name: testpod
    image: python:3.12
    #volumeMounts:
    #- name: html
    #  mountPath: /usr/share/nginx/html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          sleep 60;
        done
  #- name: 2nd
  #  image: debian
  #  volumeMounts:
  #  - name: html
  #    mountPath: /html
  #  command: ["/bin/sh", "-c"]
  #  args:
  #    - while true; do
  #        date >> /html/index.html;
  #        sleep 1;
  #      done
