---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault2
  namespace: test
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: myvaultsecret
  data:
  - secretKey: myvalue    # key inside the secret you'd like to populate
    remoteRef:
      key: cubbyhole/foo
      version: v1
      property: bar
