# https://external-secrets.io/v0.4.3/provider-hashicorp-vault/
# https://github.com/digitalocean/Kubernetes-Starter-Kit-Developers/blob/main/06-kubernetes-secrets/external-secrets-operator.md

# vault kv put -tls-skip-verify cubbyhole/foo my-value=s3cr3t

# $ vault kv get -tls-skip-verify cubbyhole/foo
# ====== Data ======
# Key         Value
# ---         -----
# my-value    s3cr3t

# $ vault kv get -tls-skip-verify -mount=cubbyhole foo
# === Data ===
# Key    Value
# ---    -----
# bar    baz


---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: myvaultsecret
  data:
  - secretKey: myvalue    # key inside the secret you'd like to populate
    remoteRef:
      key: cubbyhole/foo
      version: v1
      property: bar
