# Any Pods exposed by a Service have the following DNS resolution available:
# pod-ipv4-address.service-name.my-namespace.svc.cluster-domain.example   

# https://external-secrets.io/v0.5.7/api-secretstore/

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      #path: /
      version: v1
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: vault
          key: token
