---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-job

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: test-job
  namespace: default

---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    metadata:
      name: test-job
    spec:
      serviceAccountName: test-job
      containers:
        - name: test-job
          image: docker.io/library/ansible:1.3
          #command: [ "/bin/bash", "-c", "--" ]
          #args: [ "cd /root/argocd-test; ls -al; ./deploy-awx.sh" ]
          #args: [ "cd /root/argocd-test; ls -al; ./deploy-awx.sh; while true; do sleep 30; done;" ]

          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
      restartPolicy: Never

#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: shpod
#  namespace: shpod
#spec:
#  serviceAccountName: shpod
#  containers:
#  - name: shpod
#    image: bretfisher/shpod
#    imagePullPolicy: Always
#    stdin: true
#    tty: true
#    env:
#    - name: HOSTIP
#      valueFrom:
#        fieldRef:
#          fieldPath: status.hostIP
#
