# https://dustinspecker.com/posts/test-ingress-in-kind/

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 53
    hostPort: 53
    protocol: TCP
  - containerPort: 53
    hostPort: 53
    protocol: UDP
  #- containerPort: 31080 # expose port 31380 of the node to port 80 on the host, later to be use by kourier or contour ingress
  #  listenAddress: 127.0.0.1
  #  hostPort: 80
- role: worker
- role: worker
- role: worker
